name: Use Lynx browser to web scrape NYT

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * Fri,Sat,Sun'
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    #- uses: actions/setup-python@v4
    #  with:
    #    python-version: '3.11'
    #    cache: 'pip'
    #- run: pip install -r requirements.txt
    #- name: Fetch latest data
    #  run: python3 scrape.py
    - name: Commit and push if it changed
      run: |-
        sudo apt update && install -y lynx
        lynx -accept_all_cookies -dump https://nytimes.com > nyt.txt
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
